server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testJapGuest?serverTimezone=CST
    username: root
    password: root
  jpa:
    #\u4F1A\u81EA\u52A8\u521B\u5EFA\u66F4\u65B0\u9A8C\u8BC1\u6570\u636E\u5E93
    hibernate:
      ddl-auto: update
    #\u8BBE\u7F6E\u6570\u636E\u5E93\u5F15\u64CE\u4E3AInnoDB
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    #\u8BBE\u7F6E\u6253\u5370SQL\u8BED\u53E5\u65B9\u4FBF\u8C03\u8BD5
    show-sql: true


