server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testjapguest?serverTimezone=CST
    username: root
    password: root

#
#spring:
#  datasource:
#     db1:
#       jdbc-url: jdbc:mysql://localhost:3306/testjapguest?serverTimezone=CST
#       username: root
#       password: root
#
#
#     db2:
#      jdbc-url: jdbc:mysql://localhost:3306/testdatasourcesguest?serverTimezone=CST
#      username: root
#      password: root
